# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: self-hosted
    
    steps:
    - name: Test Things
      uses: actions/checkout@v2
    - run: |
        mysql --version
        docker --version
        echo "Hello World"
        garbage
    - name: Cleanup
      if: ${{ always() }}
      run: printf "Yes"
